# Generated by Django 4.2.2 on 2023-07-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_meep_facebook_meep_homepage_link_meep_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='homepage_link',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='profile_bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='homepage_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinterest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
