# Generated by Django 4.2.2 on 2023-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_remove_meep_facebook_remove_meep_homepage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
